### ISSUE TITLE
After running craftable new --lts my_project, database setup aborted

### ISSUE THREAD

**Issue by purplebolt** [BRACKETS-by-TRIAD/craftable#145]
I ran `craftable new --lts my_project` and everything went smoothly until its time to setup the database. I got the following message hence application couldn't run successfully.

`What database driver do you use? [pgsql]:`
  `[0] mysql`
  `[1] pgsql`
 >

`  Aborted.`

**Comment by fnematov** [comment]
I have this error to. Have you find any solution?

**Comment by palypster** [comment]
you can:

1. try it without `--no-install` flag 
1. update your `.env` file manually
1. run `php artisan craftable:install` manually

let me know if that helps

**Comment by palypster** [comment]
UPDATE:
This is the issue we are experiencing from the very beginning, but it goes beynd Craftable - the problem is in the Laravel core, so we can do nothing about it.

The problem is always only on Windows OS, but not all Windows machines are broken. We think it has something to do with the shell you are using on Windows, but we are unable to provide more information as long as we don't use Windows much.

We can only recommend you to try using different shell or proposed workaround to manually edit the environment yourself.

**Comment by djpolmd** [comment]
LOL: The same issue on Ubuntu.
