### ISSUE TITLE
Filter listings by date

### ISSUE THREAD

**Issue by BlackDeer** [BRACKETS-by-TRIAD/craftable#163]
I have a date column I'd like to filter my listing by.
I need to be able to select range which flatpickr provides with `mode: 'range'`
I need to be able to query the model by this column.
I've tried to: 
- extend the model's Listing and add something like
```
import AppListing from '../app-components/Listing/AppForm';
Vue.component('sale-listing', {
    mixins: [AppListing],
    data: function() {
        return {
            datePickerConfig: {
                mode: 'range'
            },
        }
    }

});
```
- utilize flatpackr 
```
<div class="input-group">
    <datetime v-model="date" :config="datePickerConfig" :mode="range" class="flatpickr" placeholder="Select date"></datetime>
    <span class="input-group-append">
        <button type="button" class="btn btn-primary" @click="filter('OrderDate', date)"><i class="fa fa-calendar"></i>&nbsp; Apply</button>
    </span>
</div>
```
- add `OrderDate` to searchable array in the controller

I haven't had much luck. I understand this feature maybe on the horrizon. But any advice for a novice on how I implement this properly and where I might look?
Thank you for your time.

**Comment by palypster** [comment]
Sorry for late reply. We do not support date range element out of the box. But server side implementation using AdminListing couldn't be easier I guess, because it provides you with query builder you can customize and add your own filters:
https://getcraftable.com/docs/5.0/listing#additional-query-modification

Let me know if that helped.

**Comment by BlackDeer** [comment]
Thanks @palypster
