### ISSUE TITLE
Creating a new user, other than admin

### ISSUE THREAD

**Issue by Ana1919** [BRACKETS-by-TRIAD/craftable#177]
How can I create a new role (different than the admin) and access to different content through authentication of that new type of user? Also, how can I CRUD those different users from an admin interface?

Really really need help

**Comment by Oppong** [comment]
**Step 1** - you should first generate role interface in the admin area by typing the command 
`php artisan admin:generate roles`

![Screenshot (28)](https://user-images.githubusercontent.com/20915556/71882964-53f3d700-312d-11ea-831f-cadf33050202.png)

Then type **yes**  when asked **_Do you want to attach generated permissions to the default role now? (yes/no) [yes]:_**

**Step 2** Run the command `npm run dev`

**Step 3**  Navigate to your admin panel and refresh. the roles created will appear under the **_content section_** . look at image below
![Screenshot (30)](https://user-images.githubusercontent.com/20915556/71884036-7686ef80-312f-11ea-9002-4c41ced4925d.png)

**Step 4** - Create a new role (for my example i used **editor** as the role)
![Screenshot (31)](https://user-images.githubusercontent.com/20915556/71884891-16914880-3131-11ea-83be-ab1ddf48ecc6.png)

**Creating new administrator (for my example i will use sub administrator and it will have a role as _Editor_)**
Select Manage access  under the **SETTINGS**  and create a `new user`

![Screenshot (33)](https://user-images.githubusercontent.com/20915556/71885296-fb730880-3131-11ea-8820-9163f5102e97.png)

Creating a new admin user (note: when creating the password it is a mix of both lower and uppercase) since i tried with all lowercase it did not work out for me

![Screenshot (34)](https://user-images.githubusercontent.com/20915556/71885567-83591280-3132-11ea-9c46-9a32faf304ee.png)

now in your manage access the new sub administrator will be created and it will be added to the admin listing. image below
![Screenshot (35)](https://user-images.githubusercontent.com/20915556/71885982-4e998b00-3133-11ea-985a-4415d18baca7.png)

i hope it helps @Ana1919

**Comment by Ana1919** [comment]
Thank you very much, it helped. Now how can I redirect this sub administrator to a different "app", after validating it in login?

**Comment by Oppong** [comment]
please go to this site [https://oppong.github.io/usingcraftable/.](url) to check on how to use getcraftable. i am still exploring getcraftable and i hope it will help any one who want to use craftable

**Comment by atta1234** [comment]
How to upload image in it like for post feature img ,i followed the docs but that's not enough i think

**Comment by realtebo** [comment]
Please, could you add this to official doc!?

**Comment by realtebo** [comment]
Please note: at step 3, after running `npm run dev` successfully, I see nothing on the role page.

In the browser console I got this error

> Vue warn]: Unknown custom element: <role-listing> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

**Comment by AshirbayBekzat** [comment]
Could Anyone help me?

**Comment by palypster** [comment]
Hi, I strongly encourage to explore our next generation product - https://craftable.pro/ which already has full Roles & Permissions management. Check out the demo:
https://demo.craftable.pro/admin/permissions
