### ISSUE TITLE
Manage users menu "Unauthorized"

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#188]
When I try to go into the "Manager users" tab aka `/admin/users` route I get a `403 | This action is unauthorized.` error, any idea why?

**Comment by elshobokshy** [comment]
Found the reason, when creating a row in the AdminUser table, I need to create a corresponding role for it in in the model_has_roles tab.

**Comment by edianogama** [comment]
I had the similar problem with this command. `php artisan admin:generate:user`. 
But it is because my userModel was put in the outside of /Models folder. 
So I used: `php artisan admin:generate:permissions users` 
for my permissions  and now my permission worked to see the folder and I created a userModel file on /Models/User to prevent the errors in controller.
If anyone else had the same problem with this architecture, it was how I solved.
