### ISSUE TITLE
Created a new role. UI doen't  see it.,

### ISSUE THREAD

**Issue by realtebo** [BRACKETS-by-TRIAD/craftable#195]
Started from scratch

Then I generated crud for roles

    php artisan admin:generate roles

Updated js

    npm run dev

On the CONTENT, I have roles, now. 
I added a new one with name 'Editor' and guard name 'editor' and saved

I ho on Manage Access -> New user 

I don't see the new role

![image](https://user-images.githubusercontent.com/1268699/74448616-8d7dd780-4e7b-11ea-9186-1829666652a0.png)

I tried to opt:cache, to exit and relogin, ... what must I do to simply pickup the new role?

**Comment by realtebo** [comment]
Also, I cannot use 

    php artisan admin:generate users


Because it try to override a lot of files related ro admin-user interface....

**Comment by elshobokshy** [comment]
I want to add that even if you manage to add the roles, the table `model_has_permissions` doesn't get filled, so the roles do not work

**Comment by realtebo** [comment]
I think we need a serious tutorial about common uses cases in the doc....  This project add some layers to Laravel, and we need to understand when/why/how to make something collaborate with someotherthing ....

**Comment by elshobokshy** [comment]
True, sadly a good project without proper documentation is just wasting a lot of time :(

**Comment by palypster** [comment]
Hey guys,

admin-generator works for a typical use case - generating CRUD for standard model represented by DB table.

Table `roles` is like any other table so generator provides full CRUD for the Role model.

But the Role model itself is already existing in the system - so you end up having two different models. On comes from the https://github.com/spatie/laravel-permission There you can find the `proper documentation` how to use the Roles & Permissions in Craftable.

I'm sorry Craftable currently does not provide any ready-to-go Roles management. You are on your own yet (we have this on our roadmap, but with low priority).

Interesting is that for some guys proposed solution actually did work. I think I've just spotted, where the problem is - you said you have used `editor` as a guard name -> it must be `admin` as long as this is the guard name you are using (probably, if you didn't changed it from Craftable's default).

Can you try please?
