### ISSUE TITLE
Suggestion : add information into documentation Examples > Relations

### ISSUE THREAD

**Issue by Misdirectionmaster** [BRACKETS-by-TRIAD/craftable#222]
Hello team.
I followed your entire "Examples > Relations" section and my code didn't work because one information is missing.

In the "Model" section, you should add : 

protected $with = ['author'];

Simple suggestion.
Regards

**Comment by RichardDominik** [comment]
Hi, thanks for your feedback. Information was added to documentation.

**Comment by verybigelephants** [comment]
perhaps it is worth noting in the documentation that you do not always want a model to have his relations loaded via `$with = ['author'];`. sometimes you might only want to load its relations only when neccessary via query biulder

i know of one project that went in a very wrong directoin because of it

**Comment by palypster** [comment]
Yes, true. So instead of defining:
`protected $with = ['author'];`

you should rather load it only within admin listing:
`$query->with(['author']);`

@Misdirectionmaster you probably missed that line in the docs

@RichardDominik can we update the docs once again please?

**Comment by Misdirectionmaster** [comment]
@palypster yes true, my bad.
