### ISSUE TITLE
Default pagination count

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#229]
How to change the default (25) pagination count and make it display everything by default?

**Comment by palypster** [comment]
Are you sure your default pagination have 25? Mine has 10.

Anyway, it's easy:
1. remove the pagination UI element
2. build admin listing query inside your controller's index method - instead of using `processRequestAndGet` rather build up your own listing

More info:
https://github.com/BRACKETS-by-TRIAD/admin-listing/blob/master/src/AdminListing.php#L154
https://www.getcraftable.com/docs/5.0/listing#advanced-usage

**Comment by elshobokshy** [comment]
Ah yes okay it's the `$request->cookie('per_page', 10)` inside the `processRequestAndGet` function was what I was looking for. My bad, thank you!
