### ISSUE TITLE
Craftable uses the same register route name as Laravel.

### ISSUE THREAD

**Issue by julianovmartins** [BRACKETS-by-TRIAD/craftable#259]
If code below is set:

`Auth::routes(['register' => false]);`

the Craftable assume this route name in:

```
Illuminate\Routing\Route {#1405 ▼
  +uri: "register"
  +methods: array:2 [▼
    0 => "GET"
    1 => "HEAD"
  ]
  +action: array:6 [▼
    "middleware" => array:1 [▶]
    "uses" => "Brackets\AdminAuth\Http\Controllers\MissingRoutesController@redirect"
    "controller" => "Brackets\AdminAuth\Http\Controllers\MissingRoutesController@redirect"
    "namespace" => "Brackets\AdminAuth\Http\Controllers"
    "where" => []
    "as" => "register"
  ]
```

so the test `Route::has('register')` still return `true`.

This forces me to use an ugly way to check if the default registration URL is disabled.

For example:

```
public function guestMenu()
{
    $menu = ['login' => route('login')];

    // if (Route::has('register')) {
    //    $menu['register'] = route('register');
    //}

    $RouteRegisterAction = Route::getRoutes()->getByName('register')->getActionName();

    if (strpos($RouteRegisterAction, 'showRegistrationForm') !== false) {
        $menu['register'] = route('register');
    }
    return $menu;
}
```

Shouldn't Craftable use another route name?

Or add in config:

```
'route_register' => false,
```

And in AdminAuthServiceProvider:
```
if(config('admin-auth.route_register', true)) {
    //This is just because in welcome.blade.php someone was lazy to check if also register route exists and ask only for login
    if (!Route::has('register')) {
        Route::middleware(['web'])->namespace('Brackets\AdminAuth\Http\Controllers')->group(function () {
            Route::get('/register', 'MissingRoutesController@redirect')->name('register');
        });
    }
}
```

**Comment by dejwCake** [comment]
As you can see, this hack was used for the purpose the comment said. In some probably older version of laravel: 
This is just because in welcome.blade.php someone was lazy to check if also register route exists and ask only for login

If in newer version of laravel this is fixed we do not need to register this route. We actually do not need it and is handled by MissingRoutesController.

However if you register in your router file the same route, this route from craftable should not be registered and your route should work.
