### ISSUE TITLE
How to add new vue Packages in this

### ISSUE THREAD

**Issue by sagardoshi08** [BRACKETS-by-TRIAD/craftable#265]
Hello @palypster,

Please guide me on how to add new **VUE packages** in this. I need to implement google MAP in this. I have tried to add https://www.npmjs.com/package/vue2-google-maps in my project but can't implement correctly. Can you please guide me or give me a document link to add new VUE packages in it so i will complete my project.

Thanks
Sagar Doshi

**Comment by sagardoshi08** [comment]
Hello @palypster any update on above issue.

**Comment by gettlin23** [comment]
Hi, I've successfully included packages by adding them in resources/js/admin/admin.js. You'll se some imports there

**Comment by sagardoshi08** [comment]
> Hi, I've successfully included packages by adding them in resources/js/admin/admin.js. You'll se some imports there

@gettlin23 I have already included packages in resources/js/admin/admin.js but what is the next step to add in form?

![image](https://user-images.githubusercontent.com/3811874/92300843-da421080-ef7b-11ea-81b5-5a2f6c366c36.png)

Please guide me.

Thanks
@sagardoshi08

**Comment by gettlin23** [comment]
I haven't used this plugin so I can't really help you, I tried on my project and had the same issue you described.
I solved it by using <gmap-map> instead of <GmapMap> [view docs](https://github.com/xkjyeah/vue-google-maps#manually)

Maybe you should try using the updated fork [gmap-vue](https://www.npmjs.com/package/gmap-vue) ?
