### ISSUE TITLE
Laravel 8 Support?

### ISSUE THREAD

**Issue by o2microsys** [BRACKETS-by-TRIAD/craftable#274]
hi, i love this package to match and i development alot of apps with it and i need to update to laravel 8 to get features of laravel 8 works in craftable so when we can get the update?

**Comment by palypster** [comment]
Hey, thx, we are preparing it. Will let you know soon, I hope very soon :)

**Comment by fadymondy** [comment]
any new update?

**Comment by FreddyCrugger** [comment]
Any news on this please?

**Comment by parmonov98** [comment]
Hey, Creator! How about the next week? is this gonna be released?
I am kinda developing the front-end part now. I'll need it. please, guys! :) I'll donate for a cup of coffee. maybe more than one. :)

**Comment by ed-fruty** [comment]
@palypster , @RichardDominik ?

If you haven't any progress we can start this and open PR.

**Comment by palypster** [comment]
Hey guys, we are having a progress (we had a review meeting on Friday). This update requires us to change few things because of some changes in `spatie/laravel-medialibrary`. Everything else is ready. I expect we will merge it for the dev testing upcoming weekend and if everything works, we will release it next Monday.

Note that it will be a new major update, but with simple upgrade guide. Wish us luck that everything goes smoothly.

**Comment by FreddyCrugger** [comment]
Cool!!! Thank you so much!

**Comment by palypster** [comment]
Guys, good news, we have just released the Laravel 8 support. Please give it a try and if anything bumbs up, let us know. Thank you.

Note: sorry, we didn't manage to update the docs yet, but the upgrade guide is just these two steps:

1. follow the Laravel upgrade guide https://laravel.com/docs/8.x/upgrade
2. follow the Spatie media-library upgrade guide https://github.com/spatie/laravel-medialibrary/blob/master/UPGRADING.md#from-v7-to-v8
