### ISSUE TITLE
One to many relationship

### ISSUE THREAD

**Issue by diegodeluca** [BRACKETS-by-TRIAD/craftable#332]
In the documentation of One to many (https://getcraftable.com/docs/7.0/relations) there is a missing instruction to insert `protected $with = ['author'];` wich is in the repository example inside the App\Models\ArticleWithRelationship.php at row 29 

Please update the docs.``

**Comment by palypster** [comment]
@RichardDominik can you add this please

**Comment by mitscho** [comment]
Thank you for mentioning this 👍. I was searching for hours why my stored values wouldn't show up in my select field. This finally fixed it.

**Comment by diegodeluca** [comment]
> Thank you for mentioning this 👍. I was searching for hours why my stored values wouldn't show up in my select field. This finally fixed it.

I'm not so skilled in PHP and I spent days on it... (a friend of mine helped me to find the issue)

**Comment by RichardDominik** [comment]
Docs were updated. Thanks for your feedbak.

**Comment by diegodeluca** [comment]
Sorry but I didn't find any update in the page ( https://getcraftable.com/docs/7.0/relations ).
For me it doesn't matter at all, but I think it can be useful for new users.

**Comment by palypster** [comment]
We have added it there, but from our own experience we actually think adding:
```protected $with = ['author'];```
is not correct, as long as it may lead to potential performance problems.

Better solution is manually eager load, that's why we have added the note:
```Note, that we have to load the relation using $query->with(['author']);.```
in couple of places in the:
https://getcraftable.com/docs/7.0/relations

docs. I hope this will help somebody an hour :)
