### ISSUE TITLE
How to update CRUD generation ?

### ISSUE THREAD

**Issue by FreddyCrugger** [BRACKETS-by-TRIAD/craftable#37]
Hello,

Let's say we generate a post crud as:
php artisan admin:generate posts

How is it possible to update changes in the CRUD done from a migration update?
It looks like you have to delete many files manually(both php and js) and rerun the command again.

I could not find any help on your website regarding this.

Thank you.

**Comment by palypster** [comment]
There is a —force flag that should do the trick.

Dňa 17. 6. 2018 o 23:58 užívateľ Benny <notifications@github.com> napísal:

**Comment by palypster** [comment]
Note that `--force` flag does not touch existing files that are updated (i.e. routes files etc.) - as long as we don't know if you have manually changed anything, so we don't touch this file again (once the routes are generated for the first time).

But about the other files - it should delete all the php classes, blades, javascripts etc. and then recreate them again reflecting latest migration. You wrote `none of them have been deleted` - are you sure that it was not deleted? Of course you see the files, because they were recreated. You can test it by editing your `TokenController` (i.e. add some comment) and then run the `admin:generate --force` and see if the comment is gone.
