### ISSUE TITLE
installed but not working

### ISSUE THREAD

**Issue by versatilegurung** [BRACKETS-by-TRIAD/craftable#38]
i installed the craftable on laravel 5.5.28
but when i go to admin/login
it shows laravel mix error

=============================
The Mix manifest does not exist. (View: /var/www/laravel/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php) (View: /var/www/laravel/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php) (View: /var/www/laravel/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php)
===========================
can anyone help ?
Thank you.

**Comment by versatilegurung** [comment]
@palypster

**Comment by palypster** [comment]
Hey @versatilegurung , if Mix manifest does not exists this typically means `npm run dev` ended with an error (which you have just pasted above). This is hard to debug for us, because for us it is working on a fresh install on both Mac and Windows machines and several environments like Homestaed or custom Docker image.

Just to be really clear, have you tried to run `npm install` and then `npm run dev` manually? Have you edited the webpack conf file somehow? What is the `npm` and `node` version on your environment? Are you using homestead? On Windows, Mac or Linux?

**Comment by versatilegurung** [comment]
i am on ubuntu server on raspberry pi3

**Comment by palypster** [comment]
Please try to be as verbose as you can, otherwise we really cannot help.

**Comment by versatilegurung** [comment]
@palypster Thank you .
