### ISSUE TITLE
Installing in my existing laravel project that use Jetstream, Laratrust and Fortify it seems is not working!

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#392]
I try to install in my existing laravel project using Jetstream, Laratrust and Fortify it seems not to be working,
is there a way to add craftable to Jetstream? or using only the crud generator for generating the cruds using Jetstream?

thanks

**Comment by palypster** [comment]
Sorry, we don't have any experience combining Craftable and Jetstream.

We are currently working on Craftable Pro that should be a solid alternative to Jetstream we hope. But for now there is no ETA of releasing it, definitely not sooner than end of this summer.

**Comment by rapgithub** [comment]
thanks for letting me know!! I wait for Craftable Pro!

**Comment by robman70** [comment]
What is the estimated date for the launch of Craftable PRO?

**Comment by palypster** [comment]
Hello, currently we don't have the exact date, but our goal is go live this year. Wish us luck! :)

**Comment by palypster** [comment]
Our plan is to keep it up-to-date with the latest versions of Laravel, but most-likely we won't be adding new features anymore.

**Comment by rapgithub** [comment]
thanks

**Comment by palypster** [comment]
> What is the estimated date for the launch of Craftable PRO?

It took us a while, but finally we made it! PRO version is out:
🥳 https://craftable.pro/

**Comment by rapgithub** [comment]
great!!! nice job!!! I am curious to use it! does it include user roles and permissions to have different type of users?
I used JetStream and laratrust to create user privileges so I am curious in the pro version of craftable! :)

**Comment by rapgithub** [comment]
Is it possible now in the pro version to have registration for different types of users with roles and permissions with possibility of crud generator other than for the admin? like laratrust does?

**Comment by timoransky** [comment]
Hi @rapgithub, thank you for your interest in Craftable PRO! 

We improved the registration process, now there is an option for users to self-register with a predefined default role. The second option is to invite users directly from the Craftable PRO interface. During this process, an administrator can select the role assigned to the invited user. You can see this in our demo at https://demo.craftable.pro/admin/craftable-pro-users. 

But your approach looks interesting as well, and I can see the need for this kind of _self-registration with the approval_ you are describing so we might end up implementing it as well. But I cannot promise you any deadline for the time being, since we have some features and improvements already planned in advance.

**Comment by rapgithub** [comment]
thanks! 

1) another thing I see the webpage of craftable pro and I see the structure of the files has a lot of references to craftable (I do not mean the logo but the code itself) I wonder if I finish a project using craftable pro is there way to avoid this craftable named files be published too for production or not? thanks

I do not like to give reference the tools I used for a specific work done!

2) also interesting in knowing if templating to change logo in registration areas and after login I think it will be something easy to do, but I wonder If craftable pro use template for this or need to go to the code to change them?

thanks!

**Comment by timoransky** [comment]
Yeah, no problem! I will try to answer all your questions 🙂

1. Some Craftable PRO files need to be published for the UI to work correctly. But since we use the Vite alias to load them, you can rename the folder with published js files however you want, as long as you change the alias as well. Regarding generated PHP files, they all default to the Craftable PRO namespace to be easier maintained. But of course, you can also reorganize those since all generated files are fully customizable and yours to edit 🙂
2. We believe we made customization a lot easier compared to the previous Craftable. As you guessed, we use Vue templates on all the important places so you can customize the logo, colors, sidebar content, and much more! You can read a bit about customization in the article I wrote: https://blog.meetbrackets.com/building-laravel-9-admin-panel-with-craftable-pro-f4d7a60594db. Although it is not mentioned in the article, replacing the content of `Logo.vue` file will update the logo everywhere (sidebar, login, registration....)

**Comment by rapgithub** [comment]
big thanks for the fast reply!! I will check that link! great job! love it!

**Comment by rapgithub** [comment]
Usually I need users to create their own profiles and each user profile is different from one user type to another I mean user profiles use different tables for profiles but linked via a polymorphic relation. can I still use polymorphic relations with users with craftable pro having users their own profiles depending of the user type selected when they registered? I think it is possible to create polymorphic relation with the users table but I ask to be sure... thanks again!

**Comment by palypster** [comment]
That's an interesting idea. Can you provide some migration files/eloquent models so we can have better understanding? Also let's move this to a correct repository - please create a new issue in https://github.com/BRACKETS-by-TRIAD/craftable-pro-docs/issues where we can discuss more details. Thank you

**Comment by rapgithub** [comment]
I will do that! thanks again!
