### ISSUE TITLE
pagination not working if primary key name is not 'id'

### ISSUE THREAD

**Issue by limione** [BRACKETS-by-TRIAD/craftable#416]
I have a model where the primary key is called 'car_id' indtead of 'id'. because of this, the generated pagination does not work. 
I set the `protected $primaryKey = 'car_id';` parameter in the model but it didn't help. 
I found out that the "orderby:id" parameter is statically set in the pagination settings (1st screen).
my model at the second screen, controller at the third, index request at the fourth
![image](https://user-images.githubusercontent.com/88341422/210239467-eb2e9528-2d8b-4dcf-941c-3eaba17aea2a.png)
![image](https://user-images.githubusercontent.com/88341422/210239582-a1ee1919-bff5-493f-b4f8-854087890ebe.png)
![image](https://user-images.githubusercontent.com/88341422/210239884-4f4ff1be-50ab-4f71-9acf-8d899ddc2439.png)
![image](https://user-images.githubusercontent.com/88341422/210239901-b44ffabb-0ada-47ea-af87-3b0cfe9ba8c3.png)
does anyone know how to fix this?
error: 
![image](https://user-images.githubusercontent.com/88341422/210240990-41787961-e5ce-402a-9347-ac8ae4a986b9.png)

should be "car_id" instead "id"

**Comment by Toniboy1** [comment]
Any CLue on this one?

**Comment by palypster** [comment]
Just to be clear - are you reporting that orderBy does not work correctly, when primary key is not named `id`? Because you said that pagination does not work, but then you had continued with orderBy report, so I'm confused. 

You can still don't use the helper method: `processRequestAndGet` which is really just an opinionated shortcut, but does not work well in all cases. Rather build the admin listing object manually:
https://getcraftable.com/docs/8.0/listing#advanced-usage

so you end up with something like:
```
$data = AdminListing::create(RcCar::class)
    ->attachOrdering($request-> input('sortBy', 'car_id'), $request->sortDirection)
    // ... add searching, pagination, ... everything you need. You can get inspiration in processRequestAndGet.
    ->get(['car_id', 'name']);
```

Let me know if that helped please.

**Comment by palypster** [comment]
Closingf due inactivity
