### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by 33sKamal** [BRACKETS-by-TRIAD/craftable#54]
i recently graft the craftable, so awesome and smooth,
but i stuck on how to manage multiple users ( Dash for admin, other for User/Student ..)
Also how to deal with relationships
Thanks :)

**Comment by palypster** [comment]
Thanks @33sKamal, we're glad you like it.

Can you be more specific? Craftable uses https://github.com/spatie/laravel-permission which provides ability to define roles. Default `Administrator` role is created in migration while installing Craftable. Roles CRUD is not part of a Craftable. This was by design, because, when you create a new role, you still must change your code and add some authorization checks based on this role, right? So we think, you can introduce new roles via migrations because they are always tight with the code.

I'm not sure if it answers your question.

**Comment by BlackDeer** [comment]
Sorry to open this back up. Is there a best practices you would recommend?
It seems like with Spatie you use it on a code level or through an artisan command stored at the database level. How would one create new roles through migrations?

Thank you.

**Comment by palypster** [comment]
Very easily and you can inspire by migration that is automatically generated during `admin:generate`, but you can of course update it freely.
This is best practice for us, because this way (when stored on a DB level) all the developers working on this project get the same settings, roles, permissions, ...

**Comment by nonso07** [comment]
I am also trying to create a multi auth by runing php artisan make:middleware IsAdmin but after the installaing the new longin override the awsom craftable login controller and since then i will be getting the following error when I log in.  lluminate\Contracts\Container\BindingResolutionException
Target class [App\Http\Controllers\Auth\Request] does not exist.
http://127.0.0.1:8000/login. Please any Idea i will appertiat
