### ISSUE TITLE
Use User table as default

### ISSUE THREAD

**Issue by DenisAlliswell** [BRACKETS-by-TRIAD/craftable#83]
Hello, guys!

First of all, thank you for all you've done with that package. It is really awesome.

I can't figure out how to setup configs to use User model and table as default for admins (not AdminUser). If it possible, before installation.

In docs [here](https://docs.getcraftable.com/v3/#/admin-auth?id=admin-auth) says too little about this.

Many thanks in advance!

**Comment by palypster** [comment]
True, it could be documented better.

We're currentluy working on improved docs. We would try to publish them in March.

**Comment by DenisAlliswell** [comment]
And what about setting up config to use User table as default? How one can do this?

**Comment by dejwCake** [comment]
To use User Model, please make changes to config/admin-auth.php in key `defaults`, change to:

```
'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
        'activations' => 'users',
    ],
```

If your user need to work with activation, add also:
```
use Brackets\AdminAuth\Activation\Contracts\CanActivate as CanActivateContract;
use Brackets\AdminAuth\Activation\Traits\CanActivate;
```

**Comment by DenisAlliswell** [comment]
Ok, thanks. As far as I understand I can't do this before installation.

It would be very useful and convenient if it will possible to choose the name for admin table before package installation. For those, who don't want to separate front users and back users (admins).

**Comment by palypster** [comment]
I understand, unfortnuately, currently this is not supported.

In Craftable v2 User model was shared amongst admin and frontend. But we found it problematic for most of our use cases that's why we have split it.

That said, there might be one (altough quite complicated) way how to do it, if you really require it. You can try to install Craftbale v2 (instead of v3) which shares the same User model for admin and frontend (it might require the location of the User model to be inside App\Models namespace) and then you upgrade to Craftable v3.

**Comment by DenisAlliswell** [comment]
Mm, sounds like a good workaround! Thank you! I'll give it a shot.
