### ISSUE TITLE
Relationships support (forms, validation, ....)

### ISSUE THREAD

**Issue by ismailDSMY** [BRACKETS-by-TRIAD/craftable#96]
I saw in the codes there is support for relationships, but I can't really find any info about this.

Can help me to point out where I should find on how to use this?

**Comment by xDefcon** [comment]
Updates about it? 
The only thing I found in the documentation is the following: https://docs.getcraftable.com/v3/#/admin-ui?id=ui-elements (multiselect paragraph). I'd love a feature that autogenerates multiselection for many-to-many relationships (like user->roles) and also a selection with autocomplete for User IDs (e.g: changing the sender_id of a post).

**Comment by palypster** [comment]
Sorry, no updates. And I can tell this is not within the list we have currently focus on.

**Comment by xDefcon** [comment]
> Sorry, no updates. And I can tell this is not within the list we have currently focus on.

You said that wouldn't be hard to implement that feature by creating it (implement the code by ourselves), but where we can start from? 
I saw that Craftable is using vue-multiselect for the front-end and I think i have to study the relative documentation first to fully understand what that component exactly does, but, in order to also have a practical example like the built-in "Roles" selection you have in the demo (edit profile page) where should i check?

**Comment by palypster** [comment]
Would be the sources of the demo project helpful? https://github.com/BRACKETS-by-TRIAD/craftable-demo

**Comment by rapgithub** [comment]
I think the best thing will be a sample not using built-in roles to understand better how the multiselect works with a different case other than roles for instance:

An article with a column field for tags with multiple select options to choose from and other select for single select... for instance author of the article...

I tried to use the sample of roles in the demo but it is not clear the documentation how to create a multiselect with multiple options and make it work in craftable... 

One sample with this clearly explained will be the best... because craftable it is great but missing samples and documentation... :(

thanks if you can do this!

**Comment by palypster** [comment]
Full demo example here: https://demo.getcraftable.com/admin/articles-with-relationships
